<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dismiss</name>
   <tag></tag>
   <elementGuidId>d402078f-d4ce-4d63-be77-a4418cc5e528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.woocommerce-store-notice__dismiss-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Dismiss')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f2dc460b-25a1-4812-bf09-efca5e1a6f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>66f41b69-1f3e-4a82-b300-1e4aebc8f62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>029df896-689f-4fd4-8733-b7acc241fbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>b83a1ac7-9ce6-42af-b00e-737b515f92b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch&quot;]/body[@class=&quot;product-template-default single single-product postid-1491 wp-custom-logo theme-noo-mebla woocommerce woocommerce-page woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>e3063eb0-4a92-43d8-9c07-ab9b589484cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dismiss')]</value>
      <webElementGuid>6e0d37cb-14e1-4642-abb1-322a559ccbbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We Work All The Holidays'])[1]/following::a[2]</value>
      <webElementGuid>ed0f656d-de7f-4d7f-aad7-939ed42ecd8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun: Closed'])[1]/following::a[2]</value>
      <webElementGuid>b9580983-616d-4354-b5cd-edcbfb83d5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dismiss']/parent::*</value>
      <webElementGuid>92580945-9d7e-4579-93a6-1137efef83bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[9]</value>
      <webElementGuid>c5c03a12-7fd6-40a4-b1e8-e2b34a3dd467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>0f210c02-9988-4f06-a6e7-4d04c6b6d1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Dismiss' or . = 'Dismiss')]</value>
      <webElementGuid>1a20719c-fdc5-4755-9fce-65381a7b8d4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
